name: Maven Verify on Push
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Maven Verify
      run: mvn verify
